vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: "%app.path.product_images%"
            upload_destination: "%kernel.project_dir%%app.path.product_images%"
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
